LOOPBACK_MODE = 1
SOMN_LOOPBACK_IP = "127.0.0.1"
SOMN_LOOPBACK_PORT = 45000
LOOPBACK_MSG_SIZE = 4
WORD_SIZE = 4

SOMN_MSG_PKT_SIZE = 19 * WORD_SIZE
SOMN_MESH_PKT_SIZE = 6 * WORD_SIZE
SOMN_ROUTE_PKT_SIZE = 4 * WORD_SIZE
